# Docker Compose for Yuragi Haptic Generator
# Production-ready full stack deployment

version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      target: production
    image: yuragi-haptic-backend:latest
    container_name: yuragi-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=4
      - CORS_ORIGINS=https://yuragi-haptic.com,https://www.yuragi-haptic.com
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/var/log:rw
      - /dev/snd:/dev/snd:rw  # For audio device access
    devices:
      - /dev/snd:/dev/snd:rw  # Audio device access
    privileged: false
    user: "1001:1001"
    networks:
      - haptic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on: []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.yuragi-haptic.com`)"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"

  # Frontend web service
  frontend:
    build:
      context: ./frontend
      target: production
    image: yuragi-haptic-frontend:latest
    container_name: yuragi-frontend
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs/nginx:/var/log/nginx:rw
    networks:
      - haptic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`yuragi-haptic.com`, `www.yuragi-haptic.com`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

networks:
  haptic-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  logs:
    driver: local