# Docker Compose override for centralized logging
# Use with: docker-compose -f docker-compose.yml -f docker-compose.logging.yml up

version: '3.8'

services:
  # Log aggregation service (Fluentd)
  fluentd:
    image: fluent/fluentd:v1.16-debian-1
    container_name: yuragi-fluentd
    restart: unless-stopped
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./config/fluentd:/fluentd/etc:ro
      - ./logs:/var/log/containers:rw
    networks:
      - haptic-network
    environment:
      FLUENTD_CONF: fluent.conf
    depends_on: []

  # ElasticSearch for log storage (optional)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: yuragi-elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - haptic-network
    profiles:
      - elk

  # Kibana for log visualization (optional)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.0
    container_name: yuragi-kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - haptic-network
    depends_on:
      - elasticsearch
    profiles:
      - elk

  # Update backend service with logging driver
  backend:
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
        tag: "backend.{{.Name}}"
        labels: "service,version"
        env: "ENVIRONMENT"

  # Update frontend service with logging driver  
  frontend:
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
        tag: "frontend.{{.Name}}"
        labels: "service,version"
        env: "NODE_ENV"

volumes:
  elasticsearch-data:
    driver: local

networks:
  haptic-network:
    external: true