# Docker Compose for Development
# Development environment with hot reloading

version: '3.8'

services:
  # Backend API service (development)
  backend:
    build:
      context: ./backend
      target: development
    image: yuragi-haptic-backend:dev
    container_name: yuragi-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=true
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:4173
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/.env.development:/app/.env:ro
      - ./logs:/var/log:rw
      - /dev/snd:/dev/snd:rw  # For audio device access
    devices:
      - /dev/snd:/dev/snd:rw  # Audio device access
    networks:
      - haptic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend web service (development)
  frontend:
    build:
      context: ./frontend
      target: development
    image: yuragi-haptic-frontend:dev
    container_name: yuragi-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_WS_BASE_URL=ws://localhost:8000
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/.env.development:/app/.env:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/vite.config.ts:/app/vite.config.ts:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json:ro
      - frontend-node-modules:/app/node_modules
    networks:
      - haptic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - backend

networks:
  haptic-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  logs:
    driver: local
  frontend-node-modules:
    driver: local